name: Node.js CI

on:
  push:
    branches: ['main', 'lesson-22-hw']
  pull_request:
    branches: ['main']

env:
  BUILD_FOLDER: ./lesson19HW

defaults:
  run:
    working-directory: ${{ env.BUILD_FOLDER }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: ${{ env.BUILD_FOLDER }}/playwright-report
          retention-days: 30

      - name: Upload Playwright test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-tests-results
          path: ${{ env.BUILD_FOLDER }}/test-results
          retention-days: 30
